// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDU3VNvTW-6H-HYzeofQCrFNywoY9VVnUo',
    appId: '1:784333132002:web:0443b8d8f7c25252dbcebb',
    messagingSenderId: '784333132002',
    projectId: 'chatapp-2f08e',
    authDomain: 'chatapp-2f08e.firebaseapp.com',
    storageBucket: 'chatapp-2f08e.firebasestorage.app',
    measurementId: 'G-HFY36TLE8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDO4Pmg8bA22pRWYuxMLZlXgN9R8sCTQg',
    appId: '1:784333132002:android:8ac0b002105225c1dbcebb',
    messagingSenderId: '784333132002',
    projectId: 'chatapp-2f08e',
    storageBucket: 'chatapp-2f08e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQSKxyHtIVz4wcbJ5WfXjZ_fT6cCI7qvo',
    appId: '1:784333132002:ios:a32c31cdf1fb4a77dbcebb',
    messagingSenderId: '784333132002',
    projectId: 'chatapp-2f08e',
    storageBucket: 'chatapp-2f08e.firebasestorage.app',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQSKxyHtIVz4wcbJ5WfXjZ_fT6cCI7qvo',
    appId: '1:784333132002:ios:a32c31cdf1fb4a77dbcebb',
    messagingSenderId: '784333132002',
    projectId: 'chatapp-2f08e',
    storageBucket: 'chatapp-2f08e.firebasestorage.app',
    iosBundleId: 'com.example.minimalChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDU3VNvTW-6H-HYzeofQCrFNywoY9VVnUo',
    appId: '1:784333132002:web:7380913e4808cc69dbcebb',
    messagingSenderId: '784333132002',
    projectId: 'chatapp-2f08e',
    authDomain: 'chatapp-2f08e.firebaseapp.com',
    storageBucket: 'chatapp-2f08e.firebasestorage.app',
    measurementId: 'G-C5WS6N3SE7',
  );
}
